# Generated by Django 3.0.3 on 2020-09-27 14:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0003_auto_20200927_1110'),
    ]

    operations = [
        migrations.AddField(
            model_name='tutorial',
            name='approval',
            field=models.NullBooleanField(),
        ),
    ]
