# Generated by Django 3.0.3 on 2020-09-29 05:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0006_auto_20200928_1516'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='desc',
            field=models.TextField(default=' '),
        ),
        migrations.AddField(
            model_name='category',
            name='icon',
            field=models.ImageField(default='', upload_to='services/images'),
        ),
        migrations.AlterField(
            model_name='purchase',
            name='Referrence_Number',
            field=models.CharField(blank=True, default='1200512640', editable=False, max_length=10, primary_key=True, serialize=False, unique=True),
        ),
    ]
