# Generated by Django 3.0.3 on 2020-09-30 11:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0008_auto_20200930_1638'),
    ]

    operations = [
        migrations.AddField(
            model_name='contactus',
            name='message',
            field=models.TextField(default=' ', verbose_name='Message'),
        ),
        migrations.AlterField(
            model_name='purchase',
            name='Referrence_Number',
            field=models.CharField(blank=True, default='8808120934', editable=False, max_length=10, primary_key=True, serialize=False, unique=True),
        ),
    ]
