# Generated by Django 3.0.3 on 2020-09-30 12:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0010_auto_20200930_1644'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='id',
        ),
        migrations.AddField(
            model_name='userprofile',
            name='email',
            field=models.EmailField(default='', max_length=100, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='purchase',
            name='Referrence_Number',
            field=models.CharField(blank=True, default='3216079908', editable=False, max_length=10, primary_key=True, serialize=False, unique=True),
        ),
    ]
