# Generated by Django 3.0.3 on 2020-09-27 05:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('queries', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='queryquestion',
            name='approval',
            field=models.NullBooleanField(),
        ),
    ]
