# Generated by Django 3.0.3 on 2020-09-27 07:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('queries', '0002_queryquestion_approval'),
    ]

    operations = [
        migrations.AlterField(
            model_name='queryquestion',
            name='approval',
            field=models.BooleanField(default=False),
        ),
    ]
